services:
  lesson_bot:
    container_name: lesson_bot
    image: lesson_bot_image
    # volumes:
    #   - D:\documents\python\docker-course:/home/docker-user/app
    build:
      context: .
    env_file: .env
    depends_on:
      - bot_db
  bot_db:
    container_name: postgres_container
    image: postgres:15
    volumes:
      - postgres_data:/data/postgres
    ports:
      - 5432:5432
    env_file: .env
  # pgadmin:
  #   container_name: pgadmin-container_name
  #   image: dpage/pgadmin4
  #   restart: on-failure
  #   volumes:
  #     - pgadmin_data:/var/lib/pgadmin
  #   ports:
  #     - 5050:80
  #   env_file: .env
volumes:
  postgres_data: # pgadmin_data:
